baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
themesDir = 'themes'
theme = 'devise'
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright Year, Your Name"
ignoreErrors = ['error-missing-instagram-accesstoken']

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About me"
    title = "About me"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/project/"
    weight = -100
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100


# Configuration Features
[params]
  description = "awesome"      # Your meta description of the site
  header_title = "Hi! I am Lawrence"                 # Your header title
  header_subtitle = "write code like as if your grandmother will maintain it" # Your header subtitle
  home_image = "/images/avatar.jpeg"
  favicon = "https://res.cloudinary.com/dtnxyivj1/image/upload/v1707192145/favicon_m3kzej.ico"
  recent_posts = 5                         # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/kingcaubalejo"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/king-lawrence-caubalejo-a7864a253/"


[deployment]